### PR TITLE
Add an option to center the segments if there is enough space to display them without scrolling

### PR DESCRIPTION
**Pull request by JosephLin**

### CODE REVIEW

**Comment by rs** [comment]
Thx

**Comment by JosephLin** [comment]
@rs could you bump the version? Not sure if I should make a PR for the podspec since I can't tag the repo.

**Comment by rs** [comment]
done (1.0.5)

**Comment by JosephLin** [comment]
thank you!

**Comment by JosephLin** [comment]
@rs sorry one more thing- could you also `pod trunk push` the updated spec?

**Pull request merged**
